const MATCH_HEADERS=['matchId','sport','familyA','familyB','houseA','houseB','court','startTime','endTime','scoreA','scoreB','status','updatedBy','updatedAt','version'];
const AUDIT_HEADERS=['timestamp','matchId','sport','familyA','familyB','oldScoreA','oldScoreB','newScoreA','newScoreB','teacherName','action','version'];
const SESSION_SECONDS=2*60*60;

function doGet(e){return json_(route_((e&&e.parameter)||{}));}
function doPost(e){try{return json_(route_(JSON.parse((e&&e.postData&&e.postData.contents)||'{}')));}catch(error){return json_({success:false,code:'BAD_REQUEST',message:error.message||'Yêu cầu không hợp lệ.'});}}
function route_(request){try{switch(request.action||'matches'){case'matches':return ok_(getMatches_());case'authenticate':return authenticateTeacher_(request);case'updateMatch':return updateMatchScore_(request);default:return fail_('UNKNOWN_ACTION','Chức năng không tồn tại.');}}catch(error){console.error(error);return fail_('SERVER_ERROR','Máy chủ xử lý thất bại. Vui lòng thử lại.');}}

function getMatches_(){const sheet=getSheet_('Matches'),values=sheet.getDataRange().getValues();if(values.length<2)return[];const headers=values[0].map(String);return values.slice(1).filter(r=>r[0]).map(row=>rowObject_(headers,row));}
function authenticateTeacher_(request){const name=String(request.teacherName||'').trim(),password=String(request.password||'');if(!name||!password)return fail_('INVALID_LOGIN','Tên đăng nhập hoặc mật khẩu chưa chính xác.');const properties=PropertiesService.getScriptProperties(),expected=properties.getProperty('TEACHER_PASSWORD_HASH'),salt=properties.getProperty('PASSWORD_SALT');if(!expected||!salt)throw new Error('Teacher password has not been configured.');if(!constantTimeEqual_(hashPassword_(password,salt),expected))return fail_('INVALID_LOGIN','Tên đăng nhập hoặc mật khẩu chưa chính xác.');const token=Utilities.getUuid()+Utilities.getUuid(),expiresAt=Date.now()+SESSION_SECONDS*1000;CacheService.getScriptCache().put('session:'+token,JSON.stringify({teacherName:name,expiresAt:expiresAt}),SESSION_SECONDS);return ok_({token:token,teacherName:name,expiresAt:expiresAt});}
function updateMatchScore_(request){const session=getSession_(request.token);if(!session)return fail_('SESSION_EXPIRED','Phiên nhập điểm đã hết hạn.');const matchId=String(request.matchId||''),scoreA=Number(request.scoreA),scoreB=Number(request.scoreB),version=Number(request.version),status=String(request.status||'completed');if(!matchId||!Number.isInteger(scoreA)||scoreA<0||!Number.isInteger(scoreB)||scoreB<0||!Number.isInteger(version)||['live','completed'].indexOf(status)<0)return fail_('INVALID_SCORE','Điểm không hợp lệ.');const lock=LockService.getScriptLock();if(!lock.tryLock(10000))return fail_('BUSY','Hệ thống đang cập nhật. Vui lòng thử lại.');try{const sheet=getSheet_('Matches'),values=sheet.getDataRange().getValues(),headers=values[0].map(String),idCol=headers.indexOf('matchId'),rowIndex=values.findIndex((row,i)=>i>0&&String(row[idCol])===matchId);if(rowIndex<1)return fail_('NOT_FOUND','Không tìm thấy trận đấu.');const current=rowObject_(headers,values[rowIndex]),currentVersion=Number(current.version)||0;if(currentVersion!==version)return fail_('CONFLICT','Kết quả trận đấu vừa được cập nhật bởi giáo viên khác. Vui lòng kiểm tra lại trước khi lưu.',current);const nextVersion=currentVersion+1,now=new Date(),updates={scoreA:scoreA,scoreB:scoreB,status:status,updatedBy:session.teacherName,updatedAt:now,version:nextVersion},nextRow=values[rowIndex].slice();headers.forEach((header,col)=>{if(Object.prototype.hasOwnProperty.call(updates,header))nextRow[col]=updates[header];});sheet.getRange(rowIndex+1,1,1,nextRow.length).setValues([nextRow]);getSheet_('AuditLog').appendRow([now,matchId,current.sport,current.familyA,current.familyB,current.scoreA,current.scoreB,scoreA,scoreB,session.teacherName,current.scoreA===null?'CREATE':'UPDATE',nextVersion]);SpreadsheetApp.flush();return ok_(Object.assign({},current,updates,{updatedAt:now.toISOString()}));}finally{lock.releaseLock();}}

function setupEvent(){const spreadsheet=SpreadsheetApp.getActive(),matches=ensureSheet_(spreadsheet,'Matches',MATCH_HEADERS),audit=ensureSheet_(spreadsheet,'AuditLog',AUDIT_HEADERS),config=ensureSheet_(spreadsheet,'Config',['key','value']);if(matches.getLastRow()>1)throw new Error('Matches already contains data. Clear it before re-running setupEvent().');const rows=buildSchedule_().map(m=>MATCH_HEADERS.map(h=>m[h]));matches.getRange(2,1,rows.length,rows[0].length).setValues(rows);config.getRange(2,1,5,2).setValues([['event','LSTS FAMILY DAY – SPORTS FRIENDLY COMPETITION'],['date','2026-08-21'],['time','13:30–15:30'],['refreshSeconds',7],['scoringMethod','raw_scores']]);[matches,audit,config].forEach(s=>{s.setFrozenRows(1);s.getRange(1,1,1,s.getLastColumn()).setFontWeight('bold').setBackground('#172131').setFontColor('#ffffff');s.autoResizeColumns(1,s.getLastColumn());});PropertiesService.getScriptProperties().setProperty('SPREADSHEET_ID',spreadsheet.getId());}
function setTeacherPassword(password){if(!password||String(password).length<8)throw new Error('Password must contain at least 8 characters.');const salt=Utilities.getUuid();PropertiesService.getScriptProperties().setProperties({PASSWORD_SALT:salt,TEACHER_PASSWORD_HASH:hashPassword_(String(password),salt)});console.log('Teacher password hash updated.');}

function buildSchedule_(){const slots=[['13:30','13:40'],['13:45','13:55'],['14:00','14:10'],['14:15','14:25'],['14:30','14:40'],['14:45','14:55'],['15:00','15:10'],['15:15','15:25']],all=[];function add(sport,first,second){slots.forEach((time,slot)=>{const pair=slot<4?first:second,n=(slot%4)*2+1;[0,1].forEach(c=>all.push({matchId:sport+'-'+time[0].replace(':','')+'-c'+(c+1),sport:sport,familyA:pair[0]+'-'+String(n+c).padStart(2,'0'),familyB:pair[1]+'-'+String(n+c).padStart(2,'0'),houseA:pair[0],houseB:pair[1],court:c+1,startTime:time[0],endTime:time[1],scoreA:'',scoreB:'',status:'upcoming',updatedBy:'',updatedAt:'',version:0}));});}add('badminton',['F','T'],['A','E']);add('volleyball',['A','E'],['F','T']);return all;}
function getSession_(token){if(!token)return null;const raw=CacheService.getScriptCache().get('session:'+token);if(!raw)return null;const session=JSON.parse(raw);return Date.now()<session.expiresAt?session:null;}
function getSpreadsheet_(){const id=PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID');return id?SpreadsheetApp.openById(id):SpreadsheetApp.getActive();}
function getSheet_(name){const sheet=getSpreadsheet_().getSheetByName(name);if(!sheet)throw new Error('Missing sheet: '+name);return sheet;}
function ensureSheet_(ss,name,headers){const sheet=ss.getSheetByName(name)||ss.insertSheet(name);sheet.clear();sheet.getRange(1,1,1,headers.length).setValues([headers]);return sheet;}
function rowObject_(headers,row){const out={};headers.forEach((h,i)=>{let value=row[i];if(value instanceof Date)value=value.toISOString();if(['scoreA','scoreB'].indexOf(h)>=0)value=value===''?null:Number(value);if(['court','version'].indexOf(h)>=0)value=Number(value)||0;out[h==='matchId'?'id':h]=value;});return out;}
function hashPassword_(password,salt){const bytes=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,salt+'|'+password,Utilities.Charset.UTF_8);return bytes.map(b=>('0'+((b<0?b+256:b).toString(16))).slice(-2)).join('');}
function constantTimeEqual_(a,b){if(a.length!==b.length)return false;let result=0;for(let i=0;i<a.length;i++)result|=a.charCodeAt(i)^b.charCodeAt(i);return result===0;}
function ok_(data){return{success:true,message:'OK',data:data};}
function fail_(code,message,data){return{success:false,code:code,message:message,data:data||null};}
function json_(payload){return ContentService.createTextOutput(JSON.stringify(payload)).setMimeType(ContentService.MimeType.JSON);}
