import{useEffect,useMemo,useState}from'react';
import{Activity,CalendarDays,Check,ChevronRight,Clock3,LogIn,LogOut,Medal,Menu,ShieldCheck,Trophy,Users,X}from'lucide-react';
import{onAuthStateChanged}from'firebase/auth';
import{auth,configured,deleteUser,microsoftSignIn,resetMatch,saveMatch,signOut,subscribeAudits,subscribeMatches,subscribeUsers,upsertUser}from'./firebase';
import{EVENT_DATE,families,houseMeta,houses,schedule,sportLabel}from'./data';
import{familyTotal,houseTotals,rankedHouses}from'./scoring';
import type{AppUser,HouseCode,Match,MatchStatus,Sport}from'./types';

type Page='home'|'live'|'schedule'|'families'|'leaderboard'|'rules'|'score'|'admin';
const pages:Record<Page,string>={home:'Trang chủ',live:'Live Score',schedule:'Lịch thi đấu',families:'Kết quả Family',leaderboard:'Bảng xếp hạng',rules:'Thể lệ',score:'Nhập điểm',admin:'Admin'};
const pathMap:Record<string,Page>={'/':'home','/live':'live','/schedule':'schedule','/families':'families','/leaderboard':'leaderboard','/rules':'rules','/score-entry':'score','/admin':'admin'};
const toPath=(p:Page)=>Object.entries(pathMap).find(([,v])=>v===p)?.[0]??'/';
const fmtTime=(v:any)=>v?.toDate?.().toLocaleString('vi-VN')??'—';
function statusNow(m:Match):MatchStatus{if(m.status==='completed')return'completed';const now=new Date();const day=now.toISOString().slice(0,10);if(day!==EVENT_DATE)return now<new Date(EVENT_DATE+'T00:00:00+07:00')?'upcoming':'completed';const minutes=now.getHours()*60+now.getMinutes(),[sh,sm]=m.startTime.split(':').map(Number),[eh,em]=m.endTime.split(':').map(Number);return minutes>=sh*60+sm&&minutes<=eh*60+em?'live':'upcoming'}
function App(){const[page,setPage]=useState<Page>(pathMap[location.pathname]??'home');const[menu,setMenu]=useState(false);const[matches,setMatches]=useState<Match[]>(configured?[]:schedule);const[account,setAccount]=useState<AppUser|null>(null);const[authReady,setAuthReady]=useState(!configured);const[notice,setNotice]=useState('');
useEffect(()=>{if(!configured)return;const a=subscribeMatches(setMatches);const b=onAuthStateChanged(auth,async u=>{if(!u?.email){setAccount(null);setAuthReady(true);return}const{doc,getDoc}=await import('firebase/firestore');const snap=await getDoc(doc((await import('./firebase')).db,'users',u.email.toLowerCase()));setAccount(snap.exists()&&snap.data().active?snap.data() as AppUser:null);setAuthReady(true)});return()=>{a();b()}} ,[]);
function nav(p:Page){history.pushState({},'',toPath(p));setPage(p);setMenu(false);scrollTo(0,0)}useEffect(()=>{const h=()=>setPage(pathMap[location.pathname]??'home');addEventListener('popstate',h);return()=>removeEventListener('popstate',h)},[]);
async function login(){try{setNotice('');setAccount(await microsoftSignIn())}catch(e:any){setNotice(e.message)}}
const allowed=page!=='score'||account;const adminAllowed=page!=='admin'||account?.role==='admin';
return <><header><button className="brand" onClick={()=>nav('home')}><span>LSTS</span><b>FAMILY DAY</b></button><nav className={menu?'open':''}>{(['home','live','schedule','families','leaderboard','rules']as Page[]).map(p=><button className={page===p?'active':''} onClick={()=>nav(p)} key={p}>{pages[p]}</button>)}{account&&<button className={page==='score'?'active':''} onClick={()=>nav('score')}>Nhập điểm</button>}{account?.role==='admin'&&<button className={page==='admin'?'active':''} onClick={()=>nav('admin')}>Admin</button>}</nav><div className="auth">{account?<button className="iconText" onClick={()=>signOut()}><LogOut/> <span>Đăng xuất</span></button>:<button className="microsoft" onClick={login}><LogIn/> <span>Sign in with Microsoft</span></button>}<button className="hamb" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>{!configured&&<div className="configBanner">Chế độ xem trước · Kết nối Firebase bằng tệp <code>.env</code> để bật đăng nhập và dữ liệu trực tiếp.</div>}{notice&&<div className="toast error">{notice}<button onClick={()=>setNotice('')}>×</button></div>}<main>{!authReady?<Empty text="Đang xác thực…"/>:!allowed?<Gate title="Khu vực dành cho giáo viên" onLogin={login}/>:!adminAllowed?<Gate title="Chỉ quản trị viên được truy cập" onLogin={login}/>:<Router page={page} nav={nav} matches={matches} account={account} notify={setNotice}/>}</main><footer><b>LSTS Family Day 2026</b><span>21.08.2026 · 13:30–15:30</span><span>FAIR PLAY · ĐOÀN KẾT · TÔN TRỌNG · HỢP TÁC</span></footer></>}

function Router({page,nav,matches,account,notify}:{page:Page;nav:(p:Page)=>void;matches:Match[];account:AppUser|null;notify:(s:string)=>void}){if(page==='schedule')return <Schedule matches={matches}/>;if(page==='families')return <Families matches={matches}/>;if(page==='leaderboard')return <Leaderboard matches={matches} full/>;if(page==='rules')return <Rules/>;if(page==='score')return <ScoreEntry matches={matches} account={account!} notify={notify}/>;if(page==='admin')return <Admin matches={matches} account={account!} notify={notify}/>;return <Dashboard matches={matches} nav={nav} liveOnly={page==='live'}/>}
function Hero(){return <section className="hero"><div className="eyebrow"><span className="pulse"/> TRỰC TIẾP · FAMILY DAY 2026</div><h1>SPORTS FRIENDLY<br/><em>COMPETITION</em></h1><p>Giao lưu thể thao · Trường Đinh Thiện Lý</p><div className="eventMeta"><span><CalendarDays/>21.08.2026</span><span><Clock3/>13:30–15:30</span></div></section>}
function Dashboard({matches,nav,liveOnly=false}:{matches:Match[];nav:(p:Page)=>void;liveOnly?:boolean}){const completed=matches.filter(m=>m.status==='completed');const current=matches.filter(m=>statusNow(m)==='live');const upcoming=matches.filter(m=>statusNow(m)==='upcoming').slice(0,4);return <><Hero/><section className="dashboard"><div className="sectionTitle"><div><small>CẬP NHẬT THEO THỜI GIAN THỰC</small><h2><Trophy/> Bảng xếp hạng House</h2></div><button className="textBtn" onClick={()=>nav('leaderboard')}>Xem chi tiết <ChevronRight/></button></div><Leaderboard matches={matches}/><div className="progress"><div><b>{completed.length} / {matches.length}</b><span>trận đã hoàn thành</span></div><div className="bar"><i style={{width:`${completed.length/matches.length*100}%`}}/></div><strong>{Math.round(completed.length/matches.length*100)}%</strong></div><div className="triple"><MatchSection title="Đang thi đấu" icon={<Activity/>} matches={current} empty="Chưa có trận đang diễn ra"/><MatchSection title="Trận tiếp theo" icon={<Clock3/>} matches={upcoming} empty="Không còn trận sắp tới"/><MatchSection title="Kết quả mới nhất" icon={<Check/>} matches={[...completed].reverse().slice(0,4)} empty="Chưa có kết quả"/></div>{liveOnly&&<HouseTable matches={matches}/>}</section></>}
function Leaderboard({matches,full=false}:{matches:Match[];full?:boolean}){const rows=rankedHouses(matches);return <section className={full?'page':'ranking'}>{full&&<PageHead kicker="LIVE RANKING" title="Bảng xếp hạng House" text="Tổng điểm được tính tự động từ điểm thực tế của 8 Family ở cả hai môn."/>}<div className="rankGrid">{rows.map((r,i)=><article className="rankCard" key={r.house} style={{'--house':houseMeta[r.house].color,'--soft':houseMeta[r.house].soft}as any}><div className="place">{r.rank<=3?['🥇','🥈','🥉'][r.rank-1]:`#${r.rank}`}</div><div><small>{r.tied?'ĐỒNG HẠNG':'XẾP HẠNG'}</small><h3>{houseMeta[r.house].name}</h3></div><strong>{r.total}<small> ĐIỂM</small></strong></article>)}</div>{full&&<HouseTable matches={matches}/>}</section>}
function HouseTable({matches}:{matches:Match[]}){return <div className="tableWrap"><table><thead><tr><th>House</th><th>Cầu lông</th><th>Bóng chuyền</th><th>Tổng</th></tr></thead><tbody>{houseTotals(matches).map(x=><tr key={x.house}><td><span className="houseDot" style={{background:houseMeta[x.house].color}}/>{houseMeta[x.house].name}</td><td>{x.badminton}</td><td>{x.volleyball}</td><td><b>{x.total}</b></td></tr>)}</tbody></table></div>}
function MatchSection({title,icon,matches,empty}:{title:string;icon:any;matches:Match[];empty:string}){return <section className="matchSection"><h3>{icon}{title}<span>{matches.length}</span></h3>{matches.length?matches.map(m=><MatchCard key={m.id} m={m}/>):<Empty text={empty}/>}</section>}
function MatchCard({m}:{m:Match}){const status=statusNow(m);return <article className="matchCard"><div className="matchTop"><span>{m.sport==='badminton'?'🏸':'🏐'} {sportLabel(m.sport)}</span><i className={status}>{status==='completed'?'HOÀN THÀNH':status==='live'?'ĐANG ĐẤU':'SẮP TỚI'}</i></div><small>{m.startTime}–{m.endTime} · Sân {m.court}</small><div className="versus"><b style={{borderColor:houseMeta[m.houseA].color}}>{m.familyA}</b><strong>{m.scoreA??'–'} <em>:</em> {m.scoreB??'–'}</strong><b style={{borderColor:houseMeta[m.houseB].color}}>{m.familyB}</b></div></article>}
function Schedule({matches}:{matches:Match[]}){const[filter,setFilter]=useState<'all'|Sport>('all');const times=[...new Set(matches.map(m=>m.startTime))];return <section className="page"><PageHead kicker="32 TRẬN · 2 MÔN · 2 SÂN" title="Lịch thi đấu" text="Toàn bộ lịch thi đấu Family Day ngày 21/08/2026."/><Filter value={filter} set={setFilter}/>{times.map(t=>{const list=matches.filter(m=>m.startTime===t&&(filter==='all'||m.sport===filter));return list.length?<section className="timeGroup" key={t}><h2><Clock3/>{t}</h2><div className="cards">{list.map(m=><MatchCard key={m.id} m={m}/>)}</div></section>:null})}</section>}
function Filter({value,set}:{value:any;set:(v:any)=>void}){return <div className="filters">{[['all','Tất cả'],['badminton','🏸 Cầu lông'],['volleyball','🏐 Bóng chuyền']].map(([v,l])=><button className={value===v?'active':''} onClick={()=>set(v)} key={v}>{l}</button>)}</div>}
function Families({matches}:{matches:Match[]}){const[sport,setSport]=useState<'all'|Sport>('all');const[house,setHouse]=useState<'all'|HouseCode>('all');const[family,setFamily]=useState('all');const visible=families.filter(f=>(house==='all'||f.startsWith(house))&&(family==='all'||f===family));return <section className="page"><PageHead kicker="32 FAMILY" title="Kết quả Family" text="Điểm từng Family theo môn và tổng điểm đã hoàn thành."/><div className="selectFilters"><select value={sport} onChange={e=>setSport(e.target.value as any)}><option value="all">Tất cả môn</option><option value="badminton">Cầu lông</option><option value="volleyball">Bóng chuyền</option></select><select value={house} onChange={e=>{setHouse(e.target.value as any);setFamily('all')}}><option value="all">Tất cả House</option>{houses.map(h=><option key={h}>{h}</option>)}</select><select value={family} onChange={e=>setFamily(e.target.value)}><option value="all">Tất cả Family</option>{families.filter(f=>house==='all'||f.startsWith(house)).map(f=><option key={f}>{f}</option>)}</select></div><div className="familyGrid">{visible.map(f=>{const ms=matches.filter(m=>(m.familyA===f||m.familyB===f)&&(sport==='all'||m.sport===sport));return <article className="familyCard" key={f} style={{'--house':houseMeta[f[0]as HouseCode].color}as any}><h2>{f}<strong>{familyTotal(matches,f)}<small> tổng điểm</small></strong></h2>{ms.map(m=><div key={m.id}><span>{m.sport==='badminton'?'🏸':'🏐'} {sportLabel(m.sport)}<small>vs {m.familyA===f?m.familyB:m.familyA}</small></span><b>{m.status==='completed'?(m.familyA===f?m.scoreA:m.scoreB):'–'}</b></div>)}</article>})}</div></section>}
function Rules(){return <section className="page rules"><PageHead kicker="ĐIỀU LỆ CHÍNH THỨC" title="Thể lệ thi đấu" text="Tổ chức Giao lưu thể thao Family Day · 21/08/2026"/><div className="fair">FAIR PLAY <i/> ĐOÀN KẾT <i/> TÔN TRỌNG <i/> HỢP TÁC</div><div className="ruleGrid"><Rule title="🏸 Cầu lông tập thể" points={['Đăng ký 01 đội nam và 01 đội nữ; mỗi đội 10 học sinh.','Mỗi trận kéo dài 10 phút: nữ thi đấu phút 0–5, nam thi đấu phút 5–10.','10 vận động viên đứng ở vị trí cố định, không di chuyển lên, xuống, trái hoặc phải.','Mỗi lượt cầu qua lưới, đội được chạm cầu tối đa 3 lần.','Di chuyển khỏi vị trí bị trừ 1 điểm/lần.','Chỉ thay người khi có sự đồng ý của trọng tài; Family tự chuẩn bị vợt.']}/><Rule title="🏐 Bóng chuyền hơi" points={['Đăng ký 10 vận động viên: 5 chính thức, 5 dự bị.','Mỗi trận kéo dài 10 phút: nữ thi đấu phút 0–5, nam thi đấu phút 5–10.','Ba người hàng trên, hai người hàng dưới; xoay theo chiều kim đồng hồ khi đổi giao bóng.','Giao bóng sau còi và trong 8 giây; phải tung bóng rời tay trước khi đánh.','Tối đa 3 lần chạm; một người không chạm liên tiếp 2 lần.','Không nhảy đập trong khu vực 2m; hàng sau không chắn bóng; không chắn phát bóng.','Đội đỡ phải chạm bóng ít nhất một lần trước khi đập; thay người phải báo trọng tài.']}/></div><Rule title="Quy định chung & an toàn" points={['Có mặt đúng giờ và chủ động tập hợp đội trước giờ thi đấu.','Mặc đồng phục thể dục trường, áo House hoặc áo Family.','Tuân thủ trọng tài và Ban tổ chức; cổ vũ văn minh, tôn trọng đối thủ.','Ưu tiên an toàn; không thực hiện hành động có nguy cơ gây chấn thương.','Cổ động viên đứng ngoài khu vực thi đấu theo điều động của Ban tổ chức.']}/><div className="scoringNote"><ShieldCheck/><div><b>Cách tính điểm House hiện tại</b><p>Điểm chung cuộc dựa trên tổng kết quả của 08 Family. Vì điều lệ không quy định quy đổi thắng/thua thành điểm 3–1–0, hệ thống cộng trực tiếp điểm thi đấu thực tế của từng Family.</p></div></div></section>}
function Rule({title,points}:{title:string;points:string[]}){return <article className="rule"><h2>{title}</h2><ul>{points.map(p=><li key={p}>{p}</li>)}</ul></article>}
function ScoreEntry({matches,account,notify}:{matches:Match[];account:AppUser;notify:(s:string)=>void}){const[sport,setSport]=useState<Sport>('badminton');return <section className="page scorePage"><PageHead kicker="KHU VỰC GIÁO VIÊN" title="Nhập điểm" text={`Đăng nhập: ${account.email}`}/><Filter value={sport} set={setSport}/><div className="entryGrid">{matches.filter(m=>m.sport===sport).map(m=><ScoreEditor key={`${m.id}-${m.version}`} m={m} email={account.email} canReset={account.role==='admin'} notify={notify}/>)}</div></section>}
function ScoreEditor({m,email,canReset,notify}:{m:Match;email:string;canReset:boolean;notify:(s:string)=>void}){const[a,setA]=useState(m.scoreA?.toString()??'');const[b,setB]=useState(m.scoreB?.toString()??'');const[busy,setBusy]=useState(false);async function submit(status:MatchStatus){if(a===''||b===''||!/^\d+$/.test(a)||!/^\d+$/.test(b)){notify('Điểm phải là số nguyên không âm và không được để trống.');return}if(m.status==='completed'&&!confirm('Kết quả đã hoàn thành. Bạn có chắc muốn thay đổi?'))return;try{setBusy(true);await saveMatch(m,+a,+b,status,email);notify('✓ Đã lưu kết quả thành công')}catch(e:any){notify(e.message==='CONFLICT'?'Xung đột: một giáo viên khác vừa cập nhật trận này. Dữ liệu mới đã được tải; vui lòng kiểm tra lại.':e.message)}finally{setBusy(false)}}async function reset(){if(!confirm(`Đặt lại trận ${m.familyA} vs ${m.familyB}?`))return;try{setBusy(true);await resetMatch(m,email);notify('Đã đặt lại trận đấu.')}catch(e:any){notify(e.message==='CONFLICT'?'Xung đột dữ liệu; vui lòng thử lại.':e.message)}finally{setBusy(false)}}return <article className="editor"><div className="matchTop"><b>{m.startTime}–{m.endTime} · Sân {m.court}</b><i className={m.status}>{m.status==='completed'?'HOÀN THÀNH':m.status==='live'?'ĐANG ĐẤU':'SẮP TỚI'}</i></div><div className="scoreInputs"><label><span>{m.familyA}</span><input inputMode="numeric" pattern="[0-9]*" value={a} onChange={e=>setA(e.target.value)} aria-label={`Điểm ${m.familyA}`}/></label><em>VS</em><label><span>{m.familyB}</span><input inputMode="numeric" pattern="[0-9]*" value={b} onChange={e=>setB(e.target.value)} aria-label={`Điểm ${m.familyB}`}/></label></div><div className="editorMeta">Cập nhật bởi <b>{m.updatedBy??'—'}</b> · phiên bản {m.version}</div><div className="actions"><button disabled={busy} onClick={()=>submit('live')}>Lưu kết quả</button><button className="complete" disabled={busy} onClick={()=>submit('completed')}><Check/> Hoàn thành</button>{canReset&&<button disabled={busy} onClick={reset}>Đặt lại</button>}</div></article>}
function Admin({matches,account,notify}:{matches:Match[];account:AppUser;notify:(s:string)=>void}){const[users,setUsers]=useState<AppUser[]>([]);const[audits,setAudits]=useState<any[]>([]);const[email,setEmail]=useState('');const[role,setRole]=useState<'teacher'|'admin'>('teacher');useEffect(()=>{const a=subscribeUsers(setUsers),b=subscribeAudits(setAudits);return()=>{a();b()}},[]);async function add(){if(!/^\S+@\S+\.\S+$/.test(email)){notify('Email không hợp lệ.');return}await upsertUser({email,role,active:true});setEmail('');notify('Đã thêm người dùng.')}return <section className="page"><PageHead kicker="QUẢN TRỊ HỆ THỐNG" title="Admin Dashboard" text={`Quản trị viên: ${account.email}`}/><div className="stats"><Stat label="Tổng trận" value={matches.length}/><Stat label="Hoàn thành" value={matches.filter(m=>m.status==='completed').length}/><Stat label="Còn lại" value={matches.filter(m=>m.status!=='completed').length}/><Stat label="Người được cấp quyền" value={users.filter(u=>u.active).length}/></div><section className="adminPanel"><h2><Users/> Quản lý người dùng</h2><div className="addUser"><input placeholder="teacher@school.edu.vn" value={email} onChange={e=>setEmail(e.target.value.toLowerCase())}/><select value={role} onChange={e=>setRole(e.target.value as any)}><option value="teacher">Teacher</option><option value="admin">Admin</option></select><button onClick={add}>Thêm người dùng</button></div><div className="tableWrap"><table><thead><tr><th>Email</th><th>Vai trò</th><th>Trạng thái</th><th>Hành động</th></tr></thead><tbody>{users.map(u=><tr key={u.email}><td>{u.email}</td><td>{u.role}</td><td><span className={u.active?'activeBadge':'offBadge'}>{u.active?'Active':'Inactive'}</span></td><td className="rowActions"><button onClick={()=>upsertUser({...u,active:!u.active})}>{u.active?'Tắt':'Bật'}</button><button disabled={u.email===account.email} onClick={()=>confirm(`Xóa ${u.email}?`)&&deleteUser(u.email)}>Xóa</button></td></tr>)}</tbody></table></div></section><section className="adminPanel"><h2><ShieldCheck/> Nhật ký chỉnh sửa điểm</h2><div className="tableWrap"><table><thead><tr><th>Thời gian</th><th>Môn / trận</th><th>Trước</th><th>Sau</th><th>Giáo viên</th></tr></thead><tbody>{audits.slice(0,100).map(a=><tr key={a.id}><td>{fmtTime(a.timestamp)}</td><td>{sportLabel(a.sport)}<br/><small>{a.matchLabel}</small></td><td>{a.previousValue?.scoreA??'–'} : {a.previousValue?.scoreB??'–'}</td><td><b>{a.newValue?.scoreA} : {a.newValue?.scoreB}</b></td><td>{a.teacher}</td></tr>)}</tbody></table></div></section></section>}
function Stat({label,value}:{label:string;value:number}){return <article><small>{label}</small><b>{value}</b></article>};function PageHead({kicker,title,text}:{kicker:string;title:string;text:string}){return <div className="pageHead"><small>{kicker}</small><h1>{title}</h1><p>{text}</p></div>};function Empty({text}:{text:string}){return <div className="empty">{text}</div>};function Gate({title,onLogin}:{title:string;onLogin:()=>void}){return <section className="gate"><ShieldCheck/><h1>{title}</h1><p>Đăng nhập bằng tài khoản Microsoft đã được quản trị viên cấp quyền.</p><button className="microsoft" onClick={onLogin}><LogIn/> Sign in with Microsoft</button></section>}
export default App;
