import{useCallback,useEffect,useState,type FormEvent}from'react';
import{Activity,CalendarDays,Check,ChevronRight,Clock3,Expand,LogIn,LogOut,Menu,ShieldCheck,Trophy,X}from'lucide-react';
import{apiConfigured,authenticateTeacher,clearSession,friendlyError,getMatches,readSession,updateMatch,writeSession,type TeacherSession}from'./api';
import{EVENT_DATE,families,houseMeta,houses,sportLabel}from'./data';
import{familyTotal,houseTotals,rankedHouses}from'./scoring';
import type{HouseCode,Match,MatchStatus,Sport}from'./types';

type Page='home'|'live'|'schedule'|'families'|'leaderboard'|'rules'|'score';
const pages:Record<Page,string>={home:'Trang chủ',live:'Live Score',schedule:'Lịch thi đấu',families:'Kết quả Family',leaderboard:'Bảng xếp hạng',rules:'Thể lệ',score:'Nhập điểm'};
const pathMap:Record<string,Page>={'/':'home','/live':'live','/schedule':'schedule','/families':'families','/results':'families','/leaderboard':'leaderboard','/ranking':'leaderboard','/rankings':'leaderboard','/rules':'rules','/score-entry':'score'};
const toPath=(p:Page)=>Object.entries(pathMap).find(([,v])=>v===p)?.[0]??'/';
function statusNow(m:Match):MatchStatus{if(m.status==='completed')return'completed';const now=new Date(),parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(now),part=(x:string)=>parts.find(p=>p.type===x)?.value??'',day=`${part('year')}-${part('month')}-${part('day')}`;if(day!==EVENT_DATE)return now<new Date(EVENT_DATE+'T00:00:00+07:00')?'upcoming':'upcoming';const minutes=+part('hour')*60 + +part('minute'),[sh,sm]=m.startTime.split(':').map(Number),[eh,em]=m.endTime.split(':').map(Number);return minutes>=sh*60+sm&&minutes<=eh*60+em?'live':'upcoming'}
const hashPage=()=>pathMap[location.hash.slice(1)||'/']??'home';
function App(){const[page,setPage]=useState<Page>(hashPage);const[menu,setMenu]=useState(false);const[matches,setMatches]=useState<Match[]>([]);const[session,setSession]=useState<TeacherSession|null>(readSession);const[dataReady,setDataReady]=useState(false);const[connected,setConnected]=useState(false);const[lastUpdated,setLastUpdated]=useState<Date|null>(null);const[notice,setNotice]=useState('');
const refresh=useCallback(async(silent=false)=>{try{const next=await getMatches();setMatches(next);setConnected(true);setDataReady(true);setLastUpdated(new Date())}catch(error){setConnected(false);setDataReady(true);if(!silent)setNotice(friendlyError(error))}},[]);
useEffect(()=>{refresh();const timer=setInterval(()=>refresh(true),7000);return()=>clearInterval(timer)},[refresh]);
useEffect(()=>{const online=()=>refresh(true),offline=()=>setConnected(false);addEventListener('online',online);addEventListener('offline',offline);return()=>{removeEventListener('online',online);removeEventListener('offline',offline)}},[refresh]);
function nav(p:Page){location.hash=toPath(p);setPage(p);setMenu(false);scrollTo(0,0)}useEffect(()=>{const h=()=>{setPage(hashPage());setMenu(false);scrollTo(0,0)};addEventListener('hashchange',h);return()=>removeEventListener('hashchange',h)},[]);
function logout(){clearSession();setSession(null);nav('home')}
return <div className={page==='live'?'liveMode':''}><header><button className="brand" onClick={()=>nav('home')}><span>LSTS</span><b>FAMILY DAY</b></button><nav className={menu?'open':''}>{(['home','live','schedule','families','leaderboard','rules','score']as Page[]).map(p=><button className={page===p?'active':''} onClick={()=>nav(p)} key={p}>{pages[p]}</button>)}</nav><div className="auth">{session&&<button className="iconText" onClick={logout}><LogOut/> <span>Thoát nhập điểm</span></button>}<button className="hamb" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>{!apiConfigured&&<div className="configBanner">Chưa cấu hình <code>VITE_APPS_SCRIPT_URL</code>. Xem README để kết nối Google Sheets.</div>}<div className={`connection ${connected?'online':'offline'}`}><span/>{connected?'LIVE':'KHÔNG THỂ KẾT NỐI'}{lastUpdated&&<small>Cập nhật {lastUpdated.toLocaleTimeString('vi-VN')}</small>}</div>{notice&&<div className="toast error">{notice}<button onClick={()=>setNotice('')}>×</button></div>}<main>{!dataReady?<Empty text="Đang kết nối…"/>:<Router page={page} nav={nav} matches={matches} session={session} setSession={setSession} refresh={refresh} notify={setNotice}/>}</main><footer><b>LSTS Family Day 2026</b><span>21.08.2026 · 13:30–15:30</span><span>FAIR PLAY · ĐOÀN KẾT · TÔN TRỌNG · HỢP TÁC</span></footer></div>}

function Router({page,nav,matches,session,setSession,refresh,notify}:{page:Page;nav:(p:Page)=>void;matches:Match[];session:TeacherSession|null;setSession:(s:TeacherSession)=>void;refresh:(silent?:boolean)=>Promise<void>;notify:(s:string)=>void}){if(page==='schedule')return <Schedule matches={matches}/>;if(page==='families')return <Families matches={matches}/>;if(page==='leaderboard')return <Leaderboard matches={matches} full/>;if(page==='rules')return <Rules/>;if(page==='score')return session?<ScoreEntry matches={matches} session={session} refresh={refresh} notify={notify}/>:<TeacherLogin onLogin={setSession}/>;return <Dashboard matches={matches} nav={nav} liveOnly={page==='live'}/>}
function Hero(){return <section className="hero"><div className="eyebrow"><span className="pulse"/> TRỰC TIẾP · FAMILY DAY 2026</div><h1>SPORTS FRIENDLY<br/><em>COMPETITION</em></h1><p>Giao lưu thể thao · Trường Đinh Thiện Lý</p><div className="eventMeta"><span><CalendarDays/>21.08.2026</span><span><Clock3/>13:30–15:30</span></div></section>}
function Dashboard({matches,nav,liveOnly=false}:{matches:Match[];nav:(p:Page)=>void;liveOnly?:boolean}){const completed=matches.filter(m=>m.status==='completed');const current=matches.filter(m=>statusNow(m)==='live');const upcoming=matches.filter(m=>statusNow(m)==='upcoming').slice(0,4);const full=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();return <>{!liveOnly&&<Hero/>}<section className="dashboard">{liveOnly&&<div className="displayHead"><div><small>TRỰC TIẾP · 21.08.2026</small><h1>LSTS FAMILY DAY <em>LIVE</em></h1></div><button onClick={full}><Expand/> Toàn màn hình</button></div>}<div className="sectionTitle"><div><small>CẬP NHẬT THEO THỜI GIAN THỰC</small><h2><Trophy/> Bảng xếp hạng House</h2></div>{!liveOnly&&<button className="textBtn" onClick={()=>nav('leaderboard')}>Xem chi tiết <ChevronRight/></button>}</div><Leaderboard matches={matches}/><div className="progress"><div><b>{completed.length} / {matches.length}</b><span>trận đã hoàn thành</span></div><div className="bar"><i style={{width:`${completed.length/matches.length*100}%`}}/></div><strong>{Math.round(completed.length/matches.length*100)}%</strong></div><div className="triple"><MatchSection title="Đang thi đấu" icon={<Activity/>} matches={current} empty="Chưa có trận đang diễn ra"/><MatchSection title="Trận tiếp theo" icon={<Clock3/>} matches={upcoming} empty="Không còn trận sắp tới"/><MatchSection title="Kết quả mới nhất" icon={<Check/>} matches={[...completed].sort((a,b)=>(b.version??0)-(a.version??0)).slice(0,4)} empty="Chưa có kết quả"/></div>{liveOnly&&<HouseTable matches={matches}/>}</section></>}
function Leaderboard({matches,full=false}:{matches:Match[];full?:boolean}){const rows=rankedHouses(matches);return <section className={full?'page':'ranking'}>{full&&<PageHead kicker="LIVE RANKING" title="Bảng xếp hạng House" text="Tổng điểm được tính tự động từ điểm thực tế của 8 Family ở cả hai môn."/>}<div className="rankGrid">{rows.map((r,i)=><article className="rankCard" key={r.house} style={{'--house':houseMeta[r.house].color,'--soft':houseMeta[r.house].soft}as any}><div className="place">{r.rank<=3?['🥇','🥈','🥉'][r.rank-1]:`#${r.rank}`}</div><div><small>{r.tied?'ĐỒNG HẠNG':'XẾP HẠNG'}</small><h3>{houseMeta[r.house].name}</h3></div><strong>{r.total}<small> ĐIỂM</small></strong></article>)}</div>{full&&<HouseTable matches={matches}/>}</section>}
function HouseTable({matches}:{matches:Match[]}){return <div className="tableWrap"><table><thead><tr><th>House</th><th>Cầu lông</th><th>Bóng chuyền</th><th>Tổng</th></tr></thead><tbody>{houseTotals(matches).map(x=><tr key={x.house}><td><span className="houseDot" style={{background:houseMeta[x.house].color}}/>{houseMeta[x.house].name}</td><td>{x.badminton}</td><td>{x.volleyball}</td><td><b>{x.total}</b></td></tr>)}</tbody></table></div>}
function MatchSection({title,icon,matches,empty}:{title:string;icon:any;matches:Match[];empty:string}){return <section className="matchSection"><h3>{icon}{title}<span>{matches.length}</span></h3>{matches.length?matches.map(m=><MatchCard key={m.id} m={m}/>):<Empty text={empty}/>}</section>}
function MatchCard({m}:{m:Match}){const status=statusNow(m);return <article className="matchCard"><div className="matchTop"><span>{m.sport==='badminton'?'🏸':'🏐'} {sportLabel(m.sport)}</span><i className={status}>{status==='completed'?'HOÀN THÀNH':status==='live'?'ĐANG ĐẤU':'SẮP TỚI'}</i></div><small>{m.startTime}–{m.endTime} · Sân {m.court}</small><div className="versus"><b style={{borderColor:houseMeta[m.houseA].color}}>{m.familyA}</b><strong>{m.scoreA??'–'} <em>:</em> {m.scoreB??'–'}</strong><b style={{borderColor:houseMeta[m.houseB].color}}>{m.familyB}</b></div></article>}
function Schedule({matches}:{matches:Match[]}){const[filter,setFilter]=useState<'all'|Sport>('all');const times=[...new Set(matches.map(m=>m.startTime))];return <section className="page"><PageHead kicker="32 TRẬN · 2 MÔN · 2 SÂN" title="Lịch thi đấu" text="Toàn bộ lịch thi đấu Family Day ngày 21/08/2026."/><Filter value={filter} set={setFilter}/>{times.map(t=>{const list=matches.filter(m=>m.startTime===t&&(filter==='all'||m.sport===filter));return list.length?<section className="timeGroup" key={t}><h2><Clock3/>{t}</h2><div className="cards">{list.map(m=><MatchCard key={m.id} m={m}/>)}</div></section>:null})}</section>}
function Filter({value,set}:{value:any;set:(v:any)=>void}){return <div className="filters">{[['all','Tất cả'],['badminton','🏸 Cầu lông'],['volleyball','🏐 Bóng chuyền']].map(([v,l])=><button className={value===v?'active':''} onClick={()=>set(v)} key={v}>{l}</button>)}</div>}
function Families({matches}:{matches:Match[]}){const[sport,setSport]=useState<'all'|Sport>('all');const[house,setHouse]=useState<'all'|HouseCode>('all');const[family,setFamily]=useState('all');const visible=families.filter(f=>(house==='all'||f.startsWith(house))&&(family==='all'||f===family));return <section className="page"><PageHead kicker="32 FAMILY" title="Kết quả Family" text="Điểm từng Family theo môn và tổng điểm đã hoàn thành."/><div className="selectFilters"><select value={sport} onChange={e=>setSport(e.target.value as any)}><option value="all">Tất cả môn</option><option value="badminton">Cầu lông</option><option value="volleyball">Bóng chuyền</option></select><select value={house} onChange={e=>{setHouse(e.target.value as any);setFamily('all')}}><option value="all">Tất cả House</option>{houses.map(h=><option key={h}>{h}</option>)}</select><select value={family} onChange={e=>setFamily(e.target.value)}><option value="all">Tất cả Family</option>{families.filter(f=>house==='all'||f.startsWith(house)).map(f=><option key={f}>{f}</option>)}</select></div><div className="familyGrid">{visible.map(f=>{const ms=matches.filter(m=>(m.familyA===f||m.familyB===f)&&(sport==='all'||m.sport===sport));return <article className="familyCard" key={f} style={{'--house':houseMeta[f[0]as HouseCode].color}as any}><h2>{f}<strong>{familyTotal(matches,f)}<small> tổng điểm</small></strong></h2>{ms.map(m=><div key={m.id}><span>{m.sport==='badminton'?'🏸':'🏐'} {sportLabel(m.sport)}<small>vs {m.familyA===f?m.familyB:m.familyA}</small></span><b>{m.status==='completed'?(m.familyA===f?m.scoreA:m.scoreB):'–'}</b></div>)}</article>})}</div></section>}
function Rules(){return <section className="page rules"><PageHead kicker="ĐIỀU LỆ CHÍNH THỨC" title="Thể lệ thi đấu" text="Tổ chức Giao lưu thể thao Family Day · 21/08/2026"/><div className="fair">FAIR PLAY <i/> ĐOÀN KẾT <i/> TÔN TRỌNG <i/> HỢP TÁC</div><div className="ruleGrid"><Rule title="🏸 Cầu lông tập thể" points={['Đăng ký 01 đội nam và 01 đội nữ; mỗi đội 10 học sinh.','Mỗi trận kéo dài 10 phút: nữ thi đấu phút 0–5, nam thi đấu phút 5–10.','10 vận động viên đứng ở vị trí cố định, không di chuyển lên, xuống, trái hoặc phải.','Mỗi lượt cầu qua lưới, đội được chạm cầu tối đa 3 lần.','Di chuyển khỏi vị trí bị trừ 1 điểm/lần.','Chỉ thay người khi có sự đồng ý của trọng tài; Family tự chuẩn bị vợt.']}/><Rule title="🏐 Bóng chuyền hơi" points={['Đăng ký 10 vận động viên: 5 chính thức, 5 dự bị.','Mỗi trận kéo dài 10 phút: nữ thi đấu phút 0–5, nam thi đấu phút 5–10.','Ba người hàng trên, hai người hàng dưới; xoay theo chiều kim đồng hồ khi đổi giao bóng.','Giao bóng sau còi và trong 8 giây; phải tung bóng rời tay trước khi đánh.','Tối đa 3 lần chạm; một người không chạm liên tiếp 2 lần.','Không nhảy đập trong khu vực 2m; hàng sau không chắn bóng; không chắn phát bóng.','Đội đỡ phải chạm bóng ít nhất một lần trước khi đập; thay người phải báo trọng tài.']}/></div><Rule title="Quy định chung & an toàn" points={['Có mặt đúng giờ và chủ động tập hợp đội trước giờ thi đấu.','Mặc đồng phục thể dục trường, áo House hoặc áo Family.','Tuân thủ trọng tài và Ban tổ chức; cổ vũ văn minh, tôn trọng đối thủ.','Ưu tiên an toàn; không thực hiện hành động có nguy cơ gây chấn thương.','Cổ động viên đứng ngoài khu vực thi đấu theo điều động của Ban tổ chức.']}/><div className="scoringNote"><ShieldCheck/><div><b>Cách tính điểm House hiện tại</b><p>Điểm chung cuộc dựa trên tổng kết quả của 08 Family. Vì điều lệ không quy định quy đổi thắng/thua thành điểm 3–1–0, hệ thống cộng trực tiếp điểm thi đấu thực tế của từng Family.</p></div></div></section>}
function Rule({title,points}:{title:string;points:string[]}){return <article className="rule"><h2>{title}</h2><ul>{points.map(p=><li key={p}>{p}</li>)}</ul></article>}
function TeacherLogin({onLogin}:{onLogin:(s:TeacherSession)=>void}){const[name,setName]=useState(sessionStorage.getItem('lsts-teacher-name')??'');const[password,setPassword]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();if(!name.trim()||!password){setError('Tên giáo viên và mật khẩu không được để trống.');return}try{setBusy(true);setError('');const session=await authenticateTeacher(name.trim(),password);sessionStorage.setItem('lsts-teacher-name',session.teacherName);writeSession(session);onLogin(session)}catch(error){setError((error as any).code==='INVALID_LOGIN'?'Tên đăng nhập hoặc mật khẩu chưa chính xác.':friendlyError(error))}finally{setBusy(false);setPassword('')}}return <section className="teacherLogin"><form onSubmit={submit}><LogIn/><small>KHU VỰC GIÁO VIÊN</small><h1>Đăng nhập nhập điểm</h1><label>Tên giáo viên<input autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="Ví dụ: Thầy Thiên"/></label><label>Mật khẩu sự kiện<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/></label>{error&&<div className="loginError">{error}</div>}<button disabled={busy}>{busy?'Đang xác thực…':'Vào trang nhập điểm'}</button></form></section>}
function ScoreEntry({matches,session,refresh,notify}:{matches:Match[];session:TeacherSession;refresh:(silent?:boolean)=>Promise<void>;notify:(s:string)=>void}){const[sport,setSport]=useState<Sport>('badminton');return <section className="page scorePage"><PageHead kicker="KHU VỰC GIÁO VIÊN" title="Nhập điểm" text={`Người nhập: ${session.teacherName}`}/><Filter value={sport} set={setSport}/><div className="entryGrid">{matches.filter(m=>m.sport===sport).map(m=><ScoreEditor key={`${m.id}-${m.version}`} m={m} session={session} refresh={refresh} notify={notify}/>)}</div></section>}
function ScoreEditor({m,session,refresh,notify}:{m:Match;session:TeacherSession;refresh:(silent?:boolean)=>Promise<void>;notify:(s:string)=>void}){const[a,setA]=useState(m.scoreA?.toString()??'');const[b,setB]=useState(m.scoreB?.toString()??'');const[busy,setBusy]=useState(false);const[state,setState]=useState<'idle'|'saving'|'saved'|'error'>('idle');async function submit(status:MatchStatus){if(a===''||b===''||!/^\d+$/.test(a)||!/^\d+$/.test(b)){setState('error');notify('Điểm phải là số nguyên không âm và không được để trống.');return}if(m.status==='completed'&&!confirm(`Kết quả trận đấu đã được lưu trước đó. Bạn có chắc muốn thay đổi?\n\nTrước: ${m.scoreA} – ${m.scoreB}\nMới: ${a} – ${b}\nNgười sửa: ${session.teacherName}`))return;try{setBusy(true);setState('saving');await updateMatch({token:session.token,matchId:m.id,version:m.version,scoreA:+a,scoreB:+b,status});setState('saved');notify('✅ Đã lưu kết quả');await refresh(true)}catch(error){setState('error');notify(`❌ ${friendlyError(error)}`);if((error as any).code==='CONFLICT')await refresh(true)}finally{setBusy(false)}}return <article className="editor"><div className="matchTop"><b>{m.startTime}–{m.endTime} · Sân {m.court}</b><i className={m.status}>{m.status==='completed'?'HOÀN THÀNH':m.status==='live'?'ĐANG ĐẤU':'SẮP TỚI'}</i></div><div className="scoreInputs"><label><span>{m.familyA}</span><input inputMode="numeric" pattern="[0-9]*" value={a} onChange={e=>{setA(e.target.value);setState('idle')}} aria-label={`Điểm ${m.familyA}`}/></label><em>VS</em><label><span>{m.familyB}</span><input inputMode="numeric" pattern="[0-9]*" value={b} onChange={e=>{setB(e.target.value);setState('idle')}} aria-label={`Điểm ${m.familyB}`}/></label></div><div className={`saveState ${state}`}>{state==='saving'?'Đang lưu…':state==='saved'?'✅ Đã lưu':state==='error'?'❌ Lưu thất bại':'Sẵn sàng'}</div><div className="editorMeta">Người nhập: <b>{m.updatedBy||'—'}</b>{Boolean(m.updatedAt)&&<> · {new Date(String(m.updatedAt)).toLocaleTimeString('vi-VN')}</>} · phiên bản {m.version}</div><div className="actions"><button className="complete" disabled={busy} onClick={()=>submit('completed')}><Check/> {busy?'Đang lưu…':'Lưu kết quả'}</button></div></article>}
function PageHead({kicker,title,text}:{kicker:string;title:string;text:string}){return <div className="pageHead"><small>{kicker}</small><h1>{title}</h1><p>{text}</p></div>};function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
export default App;
