import {getApp,getApps,initializeApp} from 'firebase/app';
import {getAuth,OAuthProvider,signInWithPopup,signOut as firebaseSignOut} from 'firebase/auth';
import {addDoc,collection,doc,getDoc,getFirestore,onSnapshot,orderBy,query,runTransaction,serverTimestamp,setDoc} from 'firebase/firestore';
import type {AppUser,Match,MatchStatus} from './types';
const config={apiKey:import.meta.env.VITE_FIREBASE_API_KEY,authDomain:import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,projectId:import.meta.env.VITE_FIREBASE_PROJECT_ID,storageBucket:import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,messagingSenderId:import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,appId:import.meta.env.VITE_FIREBASE_APP_ID};
export const configured=Boolean(config.apiKey&&config.projectId);
const app=getApps().length?getApp():initializeApp(configured?config:{apiKey:'demo',authDomain:'demo.invalid',projectId:'demo'});export const auth=getAuth(app);export const db=getFirestore(app);
export async function microsoftSignIn(){const p=new OAuthProvider('microsoft.com');const tenant=import.meta.env.VITE_MICROSOFT_TENANT;if(tenant&&tenant!=='common')p.setCustomParameters({tenant});const credential=await signInWithPopup(auth,p);const email=credential.user.email?.toLowerCase();if(!email)throw new Error('Microsoft did not return a verified email.');const snap=await getDoc(doc(db,'users',email));if(!snap.exists()||!snap.data().active){await firebaseSignOut(auth);throw new Error('Tài khoản này chưa được cấp quyền hoặc đã bị vô hiệu hóa.')}return snap.data() as AppUser}
export const signOut=()=>firebaseSignOut(auth);
export function subscribeMatches(cb:(m:Match[],fromCache:boolean)=>void,onError:(e:Error)=>void){return onSnapshot(collection(db,'matches'),{includeMetadataChanges:true},s=>cb(s.docs.map(d=>({id:d.id,...d.data()} as Match)),s.metadata.fromCache),onError)}
export async function saveMatch(match:Match,scoreA:number,scoreB:number,status:MatchStatus,email:string){const ref=doc(db,'matches',match.id);await runTransaction(db,async tx=>{const current=await tx.get(ref);if(!current.exists())throw new Error('Match no longer exists.');const data=current.data() as Match;if((data.version??0)!==match.version)throw new Error('CONFLICT');const nextVersion=(data.version??0)+1,before={scoreA:data.scoreA??null,scoreB:data.scoreB??null,status:data.status};tx.update(ref,{scoreA,scoreB,status,updatedBy:email,updatedAt:serverTimestamp(),version:nextVersion});tx.set(doc(db,'auditLogs',`${match.id}-v${nextVersion}`),{matchId:match.id,version:nextVersion,sport:match.sport,matchLabel:`${match.familyA} vs ${match.familyB}`,previousValue:before,newValue:{scoreA,scoreB,status},teacher:email,timestamp:serverTimestamp()})})}
export async function resetMatch(match:Match,email:string){const ref=doc(db,'matches',match.id);await runTransaction(db,async tx=>{const current=await tx.get(ref);if(!current.exists())throw new Error('Match no longer exists.');const data=current.data() as Match;if((data.version??0)!==match.version)throw new Error('CONFLICT');const nextVersion=(data.version??0)+1;tx.update(ref,{scoreA:null,scoreB:null,status:'upcoming',updatedBy:email,updatedAt:serverTimestamp(),version:nextVersion});tx.set(doc(db,'auditLogs',`${match.id}-v${nextVersion}`),{matchId:match.id,version:nextVersion,sport:match.sport,matchLabel:`${match.familyA} vs ${match.familyB}`,previousValue:{scoreA:data.scoreA??null,scoreB:data.scoreB??null,status:data.status},newValue:{scoreA:null,scoreB:null,status:'upcoming'},teacher:email,action:'reset',timestamp:serverTimestamp()})})}
export async function upsertUser(user:AppUser){await setDoc(doc(db,'users',user.email.toLowerCase()),{...user,email:user.email.toLowerCase(),createdAt:serverTimestamp()},{merge:true})}
export async function deleteUser(email:string){const {deleteDoc}=await import('firebase/firestore');await deleteDoc(doc(db,'users',email))}
export function subscribeUsers(cb:(u:AppUser[])=>void){return onSnapshot(collection(db,'users'),s=>cb(s.docs.map(d=>d.data() as AppUser)))}
export function subscribeAudits(cb:(a:any[])=>void){return onSnapshot(query(collection(db,'auditLogs'),orderBy('timestamp','desc')),s=>cb(s.docs.map(d=>({id:d.id,...d.data()}))))}
